security:
    password_hashers:
        App\Entity\UserAccount:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserAccount
                property: username  # ✅ login par username (HEAD)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: front_acceuil

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER]
        ROLE_MANAGER: [ROLE_USER]

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/backoffice, roles: ROLE_ADMIN }
        - { path: ^/frontoffice, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/recruitment, roles: ROLE_MANAGER }
        - { path: ^/admin, roles: ROLE_MANAGER }
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\UserAccount:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10